---
- name: Install smartmontools
  apt:
    name: "{{ smartmontools_packages }}"
    state: present

- name: Divert smartd configuration file
  command: >
    dpkg-divert --quiet --local --divert
    /etc/smartd.conf.dpkg-divert
    --rename /etc/smartd.conf
  args:
    creates: /etc/smartd.conf.dpkg-divert

- name: Install smartd configuration
  template:
    src: smartd.conf.j2
    dest: /etc/smartd.conf
    mode: 0644
  notify: restart smartd

- name: Install smartmontools run scripts
  copy:
    content: "{{ item.value.content if item.value is mapping else item.value }}"
    dest: "/etc/smartmontools/run.d/{{ item.key }}"
    mode: "{{ item.value.mode | d('0755') }}"
    owner: "{{ item.value.owner | d('root') }}"
    group: "{{ item.value.group | d('root') }}"
  loop: "{{ _smartmontools_run_scripts | dict2items }}"
  vars:
    _smartmontools_run_scripts: >-
      {{ smartmontools_run_scripts |
      combine(smartmontools_group_run_scripts) |
      combine(smartmontools_host_run_scripts) }}

- name: Update smartd drive database
  command:
    cmd: update-smart-drivedb
  when: smartmontools_update_drivedb
  notify: restart smartd
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable and start smartd
  service:
    name: smartd
    enabled: "{{ smartmontools_service_enabled }}"
    state: "{{ smartmontools_service_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
