---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure smartmontools is installed
      stat:
        path: "/usr/sbin/smartd"
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure value of smartmontools_rules is present in configuration
      command:
        argv:
          - grep
          - -q
          - ^# smartmontools entry$
          - /etc/smartd.conf
      changed_when: false

    - name: Ensure value of smartmontools_group_rules is present in configuration
      command:
        argv:
          - grep
          - -q
          - ^# smartmontools group entry$
          - /etc/smartd.conf
      changed_when: false

    - name: Ensure rule from smartmontools_host_rules is present in configuration
      command:
        argv:
          - grep
          - -q
          - ^# smartmontools host entry$
          - /etc/smartd.conf
      changed_when: false

    - name: Ensure smartmontools service is running
      service:
        name: smartmontools
        state: started
      check_mode: true
      register: _smartmontools_service
      failed_when: _smartmontools_service.changed
