---
smartmontools_config: >
  # smartmontools entry
smartmontools_group_config: >
  # smartmontools group entry

smartmontools_group_run_scripts:
  20test:
    content: |
      #!/bin/bash
      exit 255
